whitelist: {jekyll-analytics}

plugins:
  - jekyll-analytics

title: Kadam Parikh
description: Human learner who is making machines learn. Experience with machine learning, web scraping, data analysis and implementing neural network architectures. Loves technology hacks..
markdown: kramdown

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-158630955-1      # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking