title: Kadam Parikh
description: Human learner who is making machines learn. Experience with machine learning, web scraping, data analysis and implementing neural network architectures. Interested in AI and Cyber Security.
markdown: kramdown